// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2lbi3oosBjzL0Hoq-HK5i6cAJ8UNlJ5Q',
    appId: '1:1038840540644:web:05abc38fc49122b8fd6bf1',
    messagingSenderId: '1038840540644',
    projectId: 'community-reporter-5b628',
    authDomain: 'community-reporter-5b628.firebaseapp.com',
    storageBucket: 'community-reporter-5b628.firebasestorage.app',
    measurementId: 'G-MPL37CRFTS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1p48Pg8jKdsN02_xMWJe0nm9-EAT06H8',
    appId: '1:1038840540644:android:4ca00ae25bbf85a3fd6bf1',
    messagingSenderId: '1038840540644',
    projectId: 'community-reporter-5b628',
    storageBucket: 'community-reporter-5b628.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTUPcnbMIJ2c8wnYaO-x6o_kZ8DQW3mi8',
    appId: '1:1038840540644:ios:827fd7d172058e83fd6bf1',
    messagingSenderId: '1038840540644',
    projectId: 'community-reporter-5b628',
    storageBucket: 'community-reporter-5b628.firebasestorage.app',
    iosBundleId: 'com.example.communityReporter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTUPcnbMIJ2c8wnYaO-x6o_kZ8DQW3mi8',
    appId: '1:1038840540644:ios:827fd7d172058e83fd6bf1',
    messagingSenderId: '1038840540644',
    projectId: 'community-reporter-5b628',
    storageBucket: 'community-reporter-5b628.firebasestorage.app',
    iosBundleId: 'com.example.communityReporter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2lbi3oosBjzL0Hoq-HK5i6cAJ8UNlJ5Q',
    appId: '1:1038840540644:web:f1dfd5820715246afd6bf1',
    messagingSenderId: '1038840540644',
    projectId: 'community-reporter-5b628',
    authDomain: 'community-reporter-5b628.firebaseapp.com',
    storageBucket: 'community-reporter-5b628.firebasestorage.app',
    measurementId: 'G-V2JBLP5J4C',
  );

}